CREATE VIEW dbo.SHS_V_DIAGNOSIS_BRIDGE_ROW
AS 

	WITH diagnosis AS ( 

		SELECT 
			diagnosisRow.DIAG_BRIDGE_KEY,
			diagnosisRow.DIAG_HASH,
			ISNULL(AD, 0) [AD_DIAG_KEY], 
			ISNULL([01], 0) [01_DIAG_KEY], 
			ISNULL([02], 0) [02_DIAG_KEY], 
			ISNULL([03], 0) [03_DIAG_KEY], 
			ISNULL([04], 0) [04_DIAG_KEY], 
			ISNULL([05], 0) [05_DIAG_KEY], 
			ISNULL([06], 0) [06_DIAG_KEY], 
			ISNULL([07], 0) [07_DIAG_KEY], 
			ISNULL([08], 0) [08_DIAG_KEY], 
			ISNULL([09], 0) [09_DIAG_KEY], 
			ISNULL([10], 0) [10_DIAG_KEY], 
			ISNULL([11], 0) [11_DIAG_KEY], 
			ISNULL([12], 0) [12_DIAG_KEY], 
			ISNULL([13], 0) [13_DIAG_KEY], 
			ISNULL([14], 0) [14_DIAG_KEY], 
			ISNULL([15], 0) [15_DIAG_KEY], 
			ISNULL([16], 0) [16_DIAG_KEY], 
			ISNULL([17], 0) [17_DIAG_KEY], 
			ISNULL([18], 0) [18_DIAG_KEY], 
			ISNULL([19], 0) [19_DIAG_KEY], 
			ISNULL([20], 0) [20_DIAG_KEY],
			ISNULL([21], 0) [21_DIAG_KEY],
			ISNULL([22], 0) [22_DIAG_KEY],
			ISNULL([23], 0) [23_DIAG_KEY],
			ISNULL([24], 0) [24_DIAG_KEY],
			ISNULL([25], 0) [25_DIAG_KEY],
			ISNULL([E1], 0) [E1_DIAG_KEY],
			ISNULL([E2], 0) [E2_DIAG_KEY],
			ISNULL([E3], 0) [E3_DIAG_KEY],
			ISNULL([E4], 0) [E4_DIAG_KEY],
			ISNULL([E5], 0) [E5_DIAG_KEY],
			ISNULL([E6], 0) [E6_DIAG_KEY],
			ISNULL([E7], 0) [E7_DIAG_KEY],
			ISNULL([E8], 0) [E8_DIAG_KEY],
			ISNULL([E9], 0) [E9_DIAG_KEY],
			ISNULL([E10], 0) [E10_DIAG_KEY],
			ISNULL([E11], 0) [E11_DIAG_KEY],
			ISNULL([E12], 0) [E12_DIAG_KEY],
			ISNULL([R1], 0) [R1_DIAG_KEY],
			ISNULL([R2], 0) [R2_DIAG_KEY],
			ISNULL([R3], 0) [R3_DIAG_KEY]
		FROM (
			SELECT
				diagnosisBridge.DIAG_BRIDGE_KEY,
				diagnosisBridge.DIAG_HASH,
				diagnosisBridge.DIAG_TYPE_CD,
				diagnosisDim.DIAG_KEY
			FROM dbo.DIAGNOSIS_BRIDGE diagnosisBridge
				JOIN dbo.DIAGNOSIS_DIM diagnosisDim ON diagnosisDim.DIAG_KEY = diagnosisBridge.DIAG_KEY
		) AS src
		PIVOT (
		
			MAX(src.DIAG_KEY)
			FOR src.DIAG_TYPE_CD
			IN (
				[AD],
				[01], 
				[02], 
				[03], 
				[04], 
				[05], 
				[06], 
				[07], 
				[08], 
				[09], 
				[10], 
				[11], 
				[12], 
				[13], 
				[14], 
				[15], 
				[16], 
				[17], 
				[18], 
				[19], 
				[20],
				[21],
				[22],
				[23],
				[24],
				[25],
				[E1],
				[E2],
				[E3],
				[E4],
				[E5],
				[E6],
				[E7],
				[E8],
				[E9],
				[E10],
				[E11],
				[E12],
				[R1],
				[R2],
				[R3]
			)
		
		) AS diagnosisRow

	), poa AS ( 
	
		SELECT 
			poaRow.DIAG_BRIDGE_KEY,
			ISNULL(AD, '') [AD_POA_IND], 
			ISNULL([01], '') [01_POA_IND], 
			ISNULL([02], '') [02_POA_IND], 
			ISNULL([03], '') [03_POA_IND], 
			ISNULL([04], '') [04_POA_IND], 
			ISNULL([05], '') [05_POA_IND], 
			ISNULL([06], '') [06_POA_IND], 
			ISNULL([07], '') [07_POA_IND], 
			ISNULL([08], '') [08_POA_IND], 
			ISNULL([09], '') [09_POA_IND], 
			ISNULL([10], '') [10_POA_IND], 
			ISNULL([11], '') [11_POA_IND], 
			ISNULL([12], '') [12_POA_IND], 
			ISNULL([13], '') [13_POA_IND], 
			ISNULL([14], '') [14_POA_IND], 
			ISNULL([15], '') [15_POA_IND], 
			ISNULL([16], '') [16_POA_IND], 
			ISNULL([17], '') [17_POA_IND], 
			ISNULL([18], '') [18_POA_IND], 
			ISNULL([19], '') [19_POA_IND], 
			ISNULL([20], '') [20_POA_IND],
			ISNULL([21], '') [21_POA_IND],
			ISNULL([22], '') [22_POA_IND],
			ISNULL([23], '') [23_POA_IND],
			ISNULL([24], '') [24_POA_IND],
			ISNULL([25], '') [25_POA_IND],
			ISNULL([E1], '') [E1_POA_IND],
			ISNULL([E2], '') [E2_POA_IND],
			ISNULL([E3], '') [E3_POA_IND],
			ISNULL([E4], '') [E4_POA_IND],
			ISNULL([E5], '') [E5_POA_IND],
			ISNULL([E6], '') [E6_POA_IND],
			ISNULL([E7], '') [E7_POA_IND],
			ISNULL([E8], '') [E8_POA_IND],
			ISNULL([E9], '') [E9_POA_IND],
			ISNULL([E10], '') [E10_POA_IND],
			ISNULL([E11], '') [E11_POA_IND],
			ISNULL([E12], '') [E12_POA_IND],
			ISNULL([R1], '') [R1_POA_IND],
			ISNULL([R2], '') [R2_POA_IND],
			ISNULL([R3], '') [R3_POA_IND]
		FROM (
			SELECT
				diagnosisBridge.DIAG_BRIDGE_KEY,
				diagnosisBridge.DIAG_TYPE_CD,
				diagnosisBridge.DIAG_POA_IND
			FROM dbo.DIAGNOSIS_BRIDGE diagnosisBridge
		) AS src
		PIVOT (
		
			MAX(src.DIAG_POA_IND)
			FOR src.DIAG_TYPE_CD
			IN (
				[AD],
				[01], 
				[02], 
				[03], 
				[04], 
				[05], 
				[06], 
				[07], 
				[08], 
				[09], 
				[10], 
				[11], 
				[12], 
				[13], 
				[14], 
				[15], 
				[16], 
				[17], 
				[18], 
				[19], 
				[20],
				[21],
				[22],
				[23],
				[24],
				[25],
				[E1],
				[E2],
				[E3],
				[E4],
				[E5],
				[E6],
				[E7],
				[E8],
				[E9],
				[E10],
				[E11],
				[E12],
				[R1],
				[R2],
				[R3]
			)
		
		) AS poaRow

	) 

	SELECT 
		diagnosis.DIAG_BRIDGE_KEY,
		diagnosis.DIAG_HASH,
		diagnosis.AD_DIAG_KEY,
		poa.AD_POA_IND,
		diagnosis.[01_DIAG_KEY],
		poa.[01_POA_IND],
		diagnosis.[02_DIAG_KEY],
		poa.[02_POA_IND],
		diagnosis.[03_DIAG_KEY],
		poa.[03_POA_IND],
		diagnosis.[04_DIAG_KEY],
		poa.[04_POA_IND],
		diagnosis.[05_DIAG_KEY],
		poa.[05_POA_IND],
		diagnosis.[06_DIAG_KEY],
		poa.[06_POA_IND],
		diagnosis.[07_DIAG_KEY],
		poa.[07_POA_IND],
		diagnosis.[08_DIAG_KEY],
		poa.[08_POA_IND],
		diagnosis.[09_DIAG_KEY],
		poa.[09_POA_IND],
		diagnosis.[10_DIAG_KEY],
		poa.[10_POA_IND],
		diagnosis.[11_DIAG_KEY],
		poa.[11_POA_IND],
		diagnosis.[12_DIAG_KEY],
		poa.[12_POA_IND],
		diagnosis.[13_DIAG_KEY],
		poa.[13_POA_IND],
		diagnosis.[14_DIAG_KEY],
		poa.[14_POA_IND],
		diagnosis.[15_DIAG_KEY],
		poa.[15_POA_IND],
		diagnosis.[16_DIAG_KEY],
		poa.[16_POA_IND],
		diagnosis.[17_DIAG_KEY],
		poa.[17_POA_IND],
		diagnosis.[18_DIAG_KEY],
		poa.[18_POA_IND],
		diagnosis.[19_DIAG_KEY],
		poa.[19_POA_IND],
		diagnosis.[20_DIAG_KEY],
		poa.[20_POA_IND],
		diagnosis.[21_DIAG_KEY],
		poa.[21_POA_IND],
		diagnosis.[22_DIAG_KEY],
		poa.[22_POA_IND],
		diagnosis.[23_DIAG_KEY],
		poa.[23_POA_IND],
		diagnosis.[24_DIAG_KEY],
		poa.[24_POA_IND],
		diagnosis.[25_DIAG_KEY],
		poa.[25_POA_IND],
		diagnosis.E1_DIAG_KEY,
		poa.E1_POA_IND,
		diagnosis.E2_DIAG_KEY,
		poa.E2_POA_IND,
		diagnosis.E3_DIAG_KEY,
		poa.E3_POA_IND,
		diagnosis.E4_DIAG_KEY,
		poa.E4_POA_IND,
		diagnosis.E5_DIAG_KEY,
		poa.E5_POA_IND,
		diagnosis.E6_DIAG_KEY,
		poa.E6_POA_IND,
		diagnosis.E7_DIAG_KEY,
		poa.E7_POA_IND,
		diagnosis.E8_DIAG_KEY,
		poa.E8_POA_IND,
		diagnosis.E9_DIAG_KEY,
		poa.E9_POA_IND,
		diagnosis.E10_DIAG_KEY,
		poa.E10_POA_IND,
		diagnosis.E11_DIAG_KEY,
		poa.E11_POA_IND,
		diagnosis.E12_DIAG_KEY,
		poa.E12_POA_IND,
		diagnosis.R1_DIAG_KEY,
		poa.R1_POA_IND,
		diagnosis.R2_DIAG_KEY,
		poa.R2_POA_IND,
		diagnosis.R3_DIAG_KEY,
		poa.R3_POA_IND
	FROM diagnosis
		JOIN poa ON poa.DIAG_BRIDGE_KEY = diagnosis.DIAG_BRIDGE_KEY